[package]
name = "storage"
version = "0.1.0"
edition = "2024"

[dependencies]
proto = { path = "../proto" }
arc-swap = "1"
bytes = "1"
derive_builder = "0.20"
memmap = "0.7"
rand = "0.9"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
crc-fast.workspace = true

[dev-dependencies]
tempdir = "0.3"
