[package]
name = "musil-broker"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[features]
default = ["standalone"]
raft = []
standalone = []

[dependencies]
storage = { package = "musil-storage", path = "../storage" }
network = { package = "musil-network", path = "../network" }
proto = { package = "musil-proto", path = "../proto" }
arc-swap = "1"
bytes = "1"
derive_builder = "0.20"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1"

[dev-dependencies]
tempdir = "0.3"
