[controller]
node_id = 1
host = "0.0.0.0"
port = 9092
topics = []

[[brokers]]
node_id = 0
host = "broker-1"
port = 9092
topics = []

[[brokers]]
node_id = 2
host = "broker-3"
port = 9092
topics = []
