[package]
name = "producer"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
tokio.workspace = true
murmur2.workspace = true
rand.workspace = true
storage.workspace = true
network = { path = "../network" }
proto = { path = "../proto" }
derive_builder.workspace = true
bytes.workspace = true
tracing.workspace = true