[package]
name = "producer"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio.workspace = true
murmur2.workspace = true
rand.workspace = true
storage.workspace = true
network = { path = "../network" }
proto = { path = "../proto" }
derive_builder.workspace = true
bytes.workspace = true
tracing.workspace = true