[package]
name = "musil-producer"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
tokio.workspace = true
murmur2.workspace = true
rand.workspace = true
storage = { workspace = true }
network = { package = "musil-network", path = "../network" }
proto = { package = "musil-proto", path = "../proto" }
derive_builder.workspace = true
bytes.workspace = true
tracing.workspace = true